name: flutter_task
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  get: ^4.6.5
  flutter_zoom_drawer: ^3.0.3
  http: ^0.13.4
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

